/*********************************************
 * liberty lending 2021
 * 
 * public class: LENDING_GlobalValue
 * 
 * created by Ray, aug 21,2021
 * 
 * store the values are referecing around the org
 * 
 ****/

public with sharing class LENDING_GlobalValue {
    
    // global defination of object type
    public static final String USER_OBJECTTYPE = 'USER_OBJECTTYPE';
    public static final String OPP_OBJECTTYPE = 'OPP_OBJECTTYPE';
    public static final String LEAD_OBJECTTYPE = 'LEAD_OBJECTTYPE';
}